version: "3"
services:
  q1-back:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./.env:/home/node/.env
      - /home/node/code/node_modules
    stdin_open: true
    tty: true
